name: 'Log Changes'
description: '🪵 A smart way of managing changes.'
inputs:
  style:
    description: 'Set the style of the changelog.'
    required: false
    default: ''
  commit_message:
    description: 'Set a custom commit message.'
    required: false
    default: 'package: publish {tag}'
  prerelease:
    description: 'Create the release as a prerelease.'
    required: false
    default: 'false'
  draft:
    description: 'Create the release as a draft.'
    required: false
    default: 'false'
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT).'
    required: false
    default: ${{ github.token }}
outputs:
  release_id:
    description: 'The id of the release.'
  tag_name:
    description: 'The tag name of the release.'
  created_at:
    description: 'The creation date of the release.'
branding:
  icon: 'arrow-up'
  color: 'blue'
runs:
  using: 'node16'
  main: 'action.js'
