name: 'update'

on:
  push:
    tags:
      - 'v*'

jobs:
  update:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Retrieve Version'
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: 'Create Release'
        uses: 'azurystudio/log@v1'

      - name: 'Commit Changelog'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git pull origin dev
          git add -A
          git commit -am "chore: publish ${{ env.VERSION }}"
          git push origin HEAD:dev
      
      - name: 'Bump Major Version'
        run: |
          short="${VERSION:0:2}"
          git tag $short -f
          git push --tags -f
